// Generated by gencpp from file my_turtlebot_navigation/MyServiceMessage.msg
// DO NOT EDIT!


#ifndef MY_TURTLEBOT_NAVIGATION_MESSAGE_MYSERVICEMESSAGE_H
#define MY_TURTLEBOT_NAVIGATION_MESSAGE_MYSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <my_turtlebot_navigation/MyServiceMessageRequest.h>
#include <my_turtlebot_navigation/MyServiceMessageResponse.h>


namespace my_turtlebot_navigation
{

struct MyServiceMessage
{

typedef MyServiceMessageRequest Request;
typedef MyServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MyServiceMessage
} // namespace my_turtlebot_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_turtlebot_navigation::MyServiceMessage > {
  static const char* value()
  {
    return "920ca5ca095e1b5230fc32da338a974c";
  }

  static const char* value(const ::my_turtlebot_navigation::MyServiceMessage&) { return value(); }
};

template<>
struct DataType< ::my_turtlebot_navigation::MyServiceMessage > {
  static const char* value()
  {
    return "my_turtlebot_navigation/MyServiceMessage";
  }

  static const char* value(const ::my_turtlebot_navigation::MyServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::my_turtlebot_navigation::MyServiceMessageRequest> should match
// service_traits::MD5Sum< ::my_turtlebot_navigation::MyServiceMessage >
template<>
struct MD5Sum< ::my_turtlebot_navigation::MyServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_turtlebot_navigation::MyServiceMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::MyServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_turtlebot_navigation::MyServiceMessageRequest> should match
// service_traits::DataType< ::my_turtlebot_navigation::MyServiceMessage >
template<>
struct DataType< ::my_turtlebot_navigation::MyServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::my_turtlebot_navigation::MyServiceMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::MyServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_turtlebot_navigation::MyServiceMessageResponse> should match
// service_traits::MD5Sum< ::my_turtlebot_navigation::MyServiceMessage >
template<>
struct MD5Sum< ::my_turtlebot_navigation::MyServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_turtlebot_navigation::MyServiceMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::MyServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_turtlebot_navigation::MyServiceMessageResponse> should match
// service_traits::DataType< ::my_turtlebot_navigation::MyServiceMessage >
template<>
struct DataType< ::my_turtlebot_navigation::MyServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::my_turtlebot_navigation::MyServiceMessage >::value();
  }
  static const char* value(const ::my_turtlebot_navigation::MyServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_TURTLEBOT_NAVIGATION_MESSAGE_MYSERVICEMESSAGE_H
