(cl:defpackage my_turtlebot_navigation-srv
  (:use )
  (:export
   "MYSERVICEMESSAGE"
   "<MYSERVICEMESSAGE-REQUEST>"
   "MYSERVICEMESSAGE-REQUEST"
   "<MYSERVICEMESSAGE-RESPONSE>"
   "MYSERVICEMESSAGE-RESPONSE"
  ))

